// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktd-xC3rCpQv_gXeziyXZuFPxUzlfVm8',
    appId: '1:196967614310:web:aa02cf9ba8993aacdb6aa7',
    messagingSenderId: '196967614310',
    projectId: 'wibble-7b271',
    authDomain: 'wibble-7b271.firebaseapp.com',
    storageBucket: 'wibble-7b271.firebasestorage.app',
    measurementId: 'G-VP65LD64P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrlHANXUPAKdEu_fD7omg_znlXdZrywN0',
    appId: '1:196967614310:android:f30c9e5b699ddbfadb6aa7',
    messagingSenderId: '196967614310',
    projectId: 'wibble-7b271',
    storageBucket: 'wibble-7b271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-vZL2vdWMQiSGUe419YyIyXm6rxe6mdI',
    appId: '1:196967614310:ios:2590cda8772f25cbdb6aa7',
    messagingSenderId: '196967614310',
    projectId: 'wibble-7b271',
    storageBucket: 'wibble-7b271.firebasestorage.app',
    iosBundleId: 'com.example.wibble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-vZL2vdWMQiSGUe419YyIyXm6rxe6mdI',
    appId: '1:196967614310:ios:2590cda8772f25cbdb6aa7',
    messagingSenderId: '196967614310',
    projectId: 'wibble-7b271',
    storageBucket: 'wibble-7b271.firebasestorage.app',
    iosBundleId: 'com.example.wibble',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktd-xC3rCpQv_gXeziyXZuFPxUzlfVm8',
    appId: '1:196967614310:web:c0fce4cf5f6d17a6db6aa7',
    messagingSenderId: '196967614310',
    projectId: 'wibble-7b271',
    authDomain: 'wibble-7b271.firebaseapp.com',
    storageBucket: 'wibble-7b271.firebasestorage.app',
    measurementId: 'G-MTFRZLEW8L',
  );

}